### ISSUE TITLE
Test and fix the program

### ISSUE THREAD

**Issue by IrynaMariukha** [IrynaMariukha/2_Individua_Formula#12]
- [x] https://github.com/IrynaMariukha/2_Individua_Formula/issues/13
- [x] https://github.com/IrynaMariukha/2_Individua_Formula/issues/14
- [ ] https://github.com/IrynaMariukha/2_Individua_Formula/issues/15
- [ ] https://github.com/IrynaMariukha/2_Individua_Formula/issues/16
