### ISSUE TITLE
Analyze the task and set up the requirements

### ISSUE THREAD

**Issue by IrynaMariukha** [IrynaMariukha/2_Individua_Formula#2]
- [x] https://github.com/IrynaMariukha/2_Individua_Formula/issues/3
- [x] https://github.com/IrynaMariukha/2_Individua_Formula/issues/17
- [x] https://github.com/IrynaMariukha/2_Individua_Formula/issues/18
