### ISSUE TITLE
Plan Solution

### ISSUE THREAD

**Issue by IrynaMariukha** [IrynaMariukha/2_Individua_Formula#7]
- [x] https://github.com/IrynaMariukha/2_Individua_Formula/issues/6
- [x] https://github.com/IrynaMariukha/2_Individua_Formula/issues/19
- [x] https://github.com/IrynaMariukha/2_Individua_Formula/issues/20
